### ISSUE TITLE
DEV: Create Testing file

### ISSUE THREAD

**Issue by Erikas-Ramanauskas** [Erikas-Ramanauskas/Project-Cauldron#4]
Create TESTING.md and structure/menu for it

**Comment by pavlo-myskov** [comment]
The basic structure of the [TESTING.md](https://github.com/Erikas-Ramanauskas/Project-Cauldron/commit/98e5d84fcf0aab2f5888ed2a5df411dcf27b6d7a#diff-4da5f2fd7bc2f11672282410e99aad91d422f9f4fb6c723abc7ef29ee5cb6906) file is ready.
